version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "80:80" #000-default.conf
      - "443:443" #default-ssl.conf
    volumes: # volumes should be avoided in production
      # write access is required for: /var/www/html/storage /var/www/html/bootstrap/cache
      - ./laravel:/var/www/html/
