version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "80:80" #000-default.conf
      - "443:443" #default-ssl.conf
    #volumes: # volumes should be avoided in production
      #- ./wwwroot:/var/www/html/:ro
      #- ./controller:/var/www/html/api/:ro
    