version: "3.9"
services:
  webapp:
    build:
      context: ./
      dockerfile: ./apache.dockerfile
      target: development
    ports:
      - "80:80/tcp" #000-default.conf
      - "443:443/tcp" #default-ssl.conf
    volumes:
      # write access is required for: /storage and /bootstrap/cache
      - ./laravel:/var/www/html/
    environment:
      - DB_HOST=database
  database:
    image: mysql
    # This line of code ensures that password authentication is the default authentication method used to connect to the database:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
    ports:
      - '3306:3306/tcp'
  # dns:
  #   image: coredns/coredns
  #   ports:
  #     - "53:53/udp"
  #   volumes:
  #     - ./coredns:/root/:ro # the root cannot be used as a volume
  #   command: -conf /root/Corefile # so we need to specify the path to a Corefile

