# docker-compose up -d --build --no-deps
# write access volumes should be avoided in production

version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "80:80/tcp" #000-default.conf
      - "443:443/tcp" #default-ssl.conf
    volumes:
      # write access is required for: /var/www/html/storage /var/www/html/bootstrap/cache
      - ./laravel:/var/www/html/
  dns:
    image: coredns/coredns
    ports:
      - "53:53/udp"
    volumes:
      - ./coredns:/root/:ro # the root cannot be used as a volume
    command: -conf /root/Corefile # so we need to specify the path to a Corefile
