version: "3.9"
services:
  webapp:
    build:
      context: ./
      dockerfile: ./apache.dockerfile
      target: development
    ports:
      - "80:80/tcp" #000-default.conf
      - "443:443/tcp" #default-ssl.conf
    volumes:
      # write access is required for: /storage and /bootstrap/cache
      - ./laravel:/var/www/html/
  database:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports: # enable localhost
      - '3306:3306/tcp'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
  dns:
    image: coredns/coredns
    ports:
      - "53:53/udp"
    volumes:
      - ./coredns:/root/:ro # the root cannot be used as a volume
    command: -conf /root/Corefile # so we need to specify the path to a Corefile

